language: node_js
node_js:
  - '8'
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
jobs:
  include:
    - stage: build
      script: 
        - npm run build
        - npm run export
    - stage: test
      script: npm run test
    - stage: e2e test & deploy 
      provider: script
      script:
        - npm run e2e:test
        - npm run e2e:test:report
        - npm run deploy
      skip_cleanup: true
      on:
        branch: master
        