language: node_js
node_js:
  - '8'
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
jobs:
  include:
    - stage: eslint & build
      name: Code quality
      script:
        - npm run eslint
        - npm run build
        - npm run export
    - stage: unit tests
      name: Unit tests (Jest)
      script: npm run test
    - stage: e2e tests & deploy
      name: End-to-end tests and deployment
      provider: script
      script:
        - npm run e2e:test || true
        - npm run e2e:test:report || true
        - npm run deploy
      skip_cleanup: true
      on:
        branch: master
