language: node_js
node_js:
  - '8'
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
jobs:
  include:
    - stage: eslint
      script: npm run eslint
    - stage: build
      script: 
        - npm run build
        - npm run export
    - stage: unit tests
      script: npm run test
    - stage: e2e tests & deploy 
      provider: script
      script:
        - npm run e2e:test || true
        - npm run e2e:test:report || true
        - npm run deploy
      skip_cleanup: true
      on:
        branch: master
        