language: node_js
node_js:
  - '8'
script: 
  - npm run build
  - npm run export
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: deploy
      provider: script
      script: npm run deploy
      skip_cleanup: true
      on:
        branch: master