language: node_js
node_js:
  - '10'
jobs:
  include:
    - stage: eslint & build
      name: Code quality and compilation
      if: branch = develop
      script:
        - npm run eslint
        - npm run build:local
        - npm run start &
        - npm run export
    - stage: unit tests
      name: Unit tests (Jest)
      if: branch = develop
      script: npm run test
    - stage: e2e tests & deploy
      name: End-to-end tests
      if: branch = develop
      provider: script
      script:
        - npm run e2e:test || true
        - npm run e2e:test:report || true
        # - npm run build
        # - npm run export
        # - npm run deploy
      skip_cleanup: true
    - stage: prod deployment
      name: Production deployment
      if: branch = master
      -script:
        - npm run build
        - npm run export
        - npm run push
